### ISSUE TITLE
Local Document Collection to Skip Literature Search

### ISSUE THREAD

**Issue by Rundon-svg** [Invalid-Null/AutomaticReviewGeneration#2]
Hi there,

Thanks for building such a useful tool! I noticed that the literature search requires SerpAPI and Elsevier API keys, but I’d like to know if I can bypass these by providing a custom set of papers I already have. I also see a "Skip Literature Search" option, so I’m curious if it’s possible to use that with my own document collection. I’m trying to work in an offline environment where the LLM setup with the OpenAI API format (e.g., Ollama).

Could you let me know:

How to specify the storage path for a local literature collection?
Any preferred formats or folder structures that would work best?
Thanks so much for your guidance!

**Comment by Super-cat-max** [comment]
You need to save your literature content in txt files, named with their DOI numbers where "/" is replaced with "_". For example: 10.1002_anie.201508731.txt. Please ensure that these files are placed in the ./Temp/LiteratureSearchWorkDir directory, as shown in the configuration image.
For review articles, make sure to append _Review.txt to the filename at the end. For example: 10.1039_D0CS00814A_Review.txt.
Additionally, please make sure to use the latest version of our program, as we have made several important updates that improve performance and functionality.
Lastly, be mindful of the API consumption. This program makes extensive use of the API, and it's important to monitor your API usage carefully to avoid any disruptions.
Please note that currently, we cannot process or recognize image files.
![819d621e977d86c89ba2c447c4c33dc](https://github.com/user-attachments/assets/17bda17a-5148-4a2f-82d6-912e2a2efda0)

**Comment by Rundon-svg** [comment]
Thank you for the clear instructions. I’ll follow the naming and storage guidelines and make sure I’m using the latest version. Much appreciated.
